### ISSUE TITLE
What are you optimizing day01/part-01.py for?

### ISSUE THREAD

**Issue by james-prior** [hakim89/adventofcode#1]
What are you optimizing day01/part-01.py for?
- minimal lines of code?
- program with fewest characters?
- fastest execution?
- smallest memory usage?
- hardest to understand?
- easiest to read?

**Comment by hakim89** [comment]
Hi James, 
I'm not really optimizing those solutions for anything in particular. I would like them to be more pythonic. And for those to be a good python exercise for myself.

**Comment by james-prior** [comment]
To be Pythonic,
- Study [The Zen of Python](https://www.python.org/dev/peps/pep-0020/).
- Watch presentations by [Brandon Rhodes](http://pyvideo.org/speaker/brandon-rhodes.html) and [Raymond Hettinger](http://pyvideo.org/speaker/raymond-hettinger.html), starting with [Transforming Code into Beautiful, Idiomatic Python](http://pyvideo.org/pycon-us-2013/transforming-code-into-beautiful-idiomatic-pytho.html).
- Study cells 1, 2, and 5 of [20161202-dojo-advent-of-code-day-01-part-1-route-distance.ipynb](http://nbviewer.jupyter.org/github/james-prior/cohpy/blob/master/20161202-dojo-advent-of-code-day-01-part-1-route-distance.ipynb).
- Subscribe to the [technical mailing list](https://mail.python.org/mailman/listinfo/centraloh) and starting with the present and working backwards, study emails in the [archive](http://mail.python.org/pipermail/centraloh/) that have "Scribbles" in their titles.
- Study code by others submitted in the [challenges](https://github.com/cohpy).
- Ask Joe and Chris to refactor your code at the dojos.

**Comment by hakim89** [comment]
Very useful links. Thank you very much
